// User Login
export const USER_LOGIN_WITH_EMAIL = 'USER_LOGIN_WITH_EMAIL';
export const USER_LOGIN_WITH_EMAIL_SUCCESS = 'USER_LOGIN_WITH_EMAIL_SUCCESS';
export const USER_LOGIN_WITH_EMAIL_ERROR = 'USER_LOGIN_WITH_EMAIL_ERROR';

// User Sign up
export const USER_SIGN_UP_WITH_EMAIL = 'USER_SIGN_UP_WITH_EMAIL';
export const USER_SIGN_UP__WITH_EMAIL_SUCCESS = 'USER_SIGN_UP__WITH_EMAIL_SUCCESS';
export const USER_SIGN_UP__WITH_EMAIL_ERROR = 'USER_SIGN_UP__WITH_EMAIL_ERROR';

// User Profile
export const USER_PROFILE_CREATE = 'USER_PROFILE_CREATE';
export const USER_PROFILE_CREATE_SUCCESS = 'USER_PROFILE_CREATE_SUCCESS';
export const USER_PROFILE_CREATE_ERROR = 'USER_PROFILE_CREATE_ERROR';
